# Generated by Django 5.1.5 on 2025-01-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='published_by',
        ),
    ]
